### ISSUE TITLE
Worksheet 11

### ISSUE THREAD

**Issue by ecyeager** [seckindemirbas/PLP#45]
Q2 is the same as Q9 in WS10 (where it is not marked as being from an old final)
Q3 needs some \left and \rights in the second displayed equation, where the function is defined
Q6: Period missing at the end of the introductory parenthetical

**Comment by ecyeager** [comment]
Q3: starts with "Let a,b,c,a" instead of "Let a,b,c,d"

**Comment by arechnitzer** [comment]
Fixed Q2 by changing Q9 in WS10.

**Comment by arechnitzer** [comment]
Cleaned up formatting and punctuation.
